fix(ci): support running update on the pr

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -56,78 +56,78 @@ jobs:
   #         purge-created: 0
   #         purge-primary-key: never
 
-  # update:
-  #   name: Update data and flakes
-  #   if: github.ref_name == 'master'
-  #   permissions:
-  #     actions: write
-  #     contents: write
-  #     pull-requests: write
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout this repo
-  #       uses: actions/checkout@v4
-  #     - name: Install Nix
-  #       uses: nixbuild/nix-quick-install-action@v30
-  #       with:
-  #         nix_conf: ${{ env.nix_conf }}
-  #     - uses: nix-community/cache-nix-action/restore@v6
-  #       with:
-  #         primary-key: nix-update-${{ hashfiles('{.,nix-dev}/*.{nix,lock}', 'haskell') }}
-  #         restore-prefixes-first-match: nix-update-
-  #     - name: Configure git
-  #       env:
-  #         # required for gh
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       run: |
-  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-  #         git config --global user.name "github-actions[bot]"
-  #     - name: Pull latest changes
-  #       run: git pull --rebase --autostash origin master
-  #     - name: Update template flake locks
-  #       run: |
-  #         cd template
-  #         nix flake update
-  #     - name: Format Nix files
-  #       run: nix fmt
-  #     - name: Save flake attributes from GC
-  #       # Need this to run before updateExtensions*
-  #       # because the following steps run GC
-  #       if: always()
-  #       run: nix profile install .#saveFromGC.ci.jobs.update
-  #     - name: Update extensions
-  #       run: nix run .#updateExtensions -- --config .github/config.yaml
-  #     - name: Update extra extensions
-  #       run: nix run .#updateExtraExtensions
-  #     - name: Commit and push changes
-  #       run: |-
-  #         git pull --rebase --autostash origin master
+  update:
+    name: Update data and flakes
+    # if: github.ref_name == 'master'
+    permissions:
+      actions: write
+      contents: write
+      pull-requests: write
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout this repo
+        uses: actions/checkout@v4
+      - name: Install Nix
+        uses: nixbuild/nix-quick-install-action@v30
+        with:
+          nix_conf: ${{ env.nix_conf }}
+      - uses: nix-community/cache-nix-action/restore@v6
+        with:
+          primary-key: nix-update-${{ hashfiles('{.,nix-dev}/*.{nix,lock}', 'haskell') }}
+          restore-prefixes-first-match: nix-update-
+      - name: Configure git
+        env:
+          # required for gh
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+      # - name: Pull latest changes
+      #   run: |
+      - name: Update template flake locks
+        run: |
+          cd template
+          nix flake update
+      - name: Format Nix files
+        run: nix fmt
+      - name: Save flake attributes from GC
+        # Need this to run before updateExtensions*
+        # because the following steps run GC
+        if: always()
+        run: nix profile install .#saveFromGC.ci.jobs.update
+      - name: Update extensions
+        run: nix run .#updateExtensions -- --config .github/config.yaml
+      - name: Update extra extensions
+        run: nix run .#updateExtraExtensions
+      - name: Commit and push changes
+        run: |-
+          # git pull --rebase --autostash origin master
 
-  #         git add .
+          git add .
 
-  #         git commit \
-  #           -m "action" \
-  #           -m "Update flake locks" \
-  #           -m "Update extensions" \
-  #           -m "Update extra extensions" \
-  #           || echo "commit failed!"
+          git commit \
+            -m "action" \
+            -m "Update flake locks" \
+            -m "Update extensions" \
+            -m "Update extra extensions" \
+            || echo "commit failed!"
 
-  #         git push
-  #     - uses: nix-community/cache-nix-action/save@v6
-  #       if: always()
-  #       with:
-  #         primary-key: nix-update-${{ hashfiles('{.,nix-dev}/*.{nix,lock}', 'haskell') }}
-  #         gc-max-store-size: 3G
-  #         purge: true
-  #         purge-prefixes: nix-update-
-  #         purge-created: 0
-  #         purge-primary-key: never
+          git push
+      - uses: nix-community/cache-nix-action/save@v6
+        if: always()
+        with:
+          primary-key: nix-update-${{ hashfiles('{.,nix-dev}/*.{nix,lock}', 'haskell') }}
+          gc-max-store-size: 3G
+          purge: true
+          purge-prefixes: nix-update-
+          purge-created: 0
+          purge-primary-key: never
 
   test-template:
     name: Test template works
     # if: github.ref_name == 'master'
-    # needs:
-      # - update
+    needs:
+      - update
       # - test
     permissions:
       actions: write
@@ -146,8 +146,13 @@ jobs:
         uses: nixbuild/nix-quick-install-action@v30
         with:
           nix_conf: ${{env.nix_conf}}
-      # - name: Pull latest changes
-      #   run: git pull --rebase --autostash origin master
+      - name: Pull latest changes
+        run: |
+          ${{
+            github.head_ref
+              && format('gh pr checkout {0}', github.event.pull_request.number) 
+              || format('git pull --rebase origin {0}', github.ref_name) 
+          }}
       - name: Restore and cache Nix store
         uses: nix-community/cache-nix-action/restore@v6
         with:
